baseURL: "https://mee2001.github.io"
languageCode: "en-us"
title: "Victor Starzec"
theme: hugo-profile

Paginate: 3
googleAnalytics: "G-CDX031CBKR"

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: dropdown
      title: Example dropdown menu
      name: Gallery
      weight: 3
    - identifier: dropdown1
      title: AV Gigs
      name: AV Gigs
      url: /av/gigs
      parent: dropdown
      weight: 1
    - identifier: dropdown2
      title: Projects
      name: Projects
      url: /#projects
      parent: dropdown
      weight: 2

params:
  title: "Portfolio"
  description: Who am I and what do I do?
  # staticPath: "static"  # The path to serve the static files from
  favicon: "/fav.png"

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Victor Starzec."
    # subtitle: "I build things for the web"
    content: |-
      Electrical and Electronic Engineering Student. Freelancer. Volunteer.

      I always strive for perfection in whatever I find myself doing.
    image: /images/victor.jpg
    button:
      enable: true
      name: "E-mail"
      url: "mailto:vs419@ic.ac.uk"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/Mee2001
        - icon: fab fa-facebook
          url: https://www.facebook.com/profile.php?id=100011084289942
      customIcons:
        - icon: /fav.png
          url: "https://mee2001.github.io"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/victor-close.jpg"
    content: |-
      I am a thrid year Electrical and Electronic Engineering student at Imperial College London. I have a strong background in mathematics, electronics and computer science. I also have a strong interest in the entertainment industry, leading backstage teams and designing systems for shows. I am currently working in R&D at [Carallon Ltd.](https://www.carallon.com/) in London, UK. 

      I am currently working on [Brompton's](https://www.bromptontech.com/) Tessera video proccessing lineup, calling on skills in software and FPGA development.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Python"
        - "C++"
        - "SystemVerilog"
        - "Verdi"
        - "VCS"
        - "TCL"
        - "QT"
        - "HTML"
        - "CSS"
        - "JavaScript"

  # Experience
  experience:
    enable: true
    items:
      - job: "Software and FPGA Engineer"
        company: "Carallon Ltd"
        companyUrl: "https://www.carallon.com/"
        date: "April 2022 - present"
        featuredLink:
          enable: true
          name: "View the project"
          url: "https://www.bromptontech.com/"
        content: "I am currently working as a software and FPGA developer at [Carallon Ltd.](https://www.carallon.com/) in London, UK. I am currently working on a project that will significantly improve the usability of the Brompton Tessera video porccessing system in future firmware releases."

      - job: "Sound Lighting and Video Design"
        company: "Sole Trader"
        companyUrl: "https://example.com"
        date: "2018 - Present"
        featuredLink:
          enable: true
          name: "Gallery"
          url: /av/gigs
        content: |-
          I offer sound, lighting, and video design services for the live events industry, working at all levels - including PM (overseeing all technical aspects of a show).
          
          Previous clients include:
          - Soho Garden Dubai
          - The London Cabaret Club
          - Corporate
          - University Societies
          - Schools
          - IC SilFest
          - IC Summer Ball

      - job: "Electronics Repair"
        company: "Device Repair"
        date: "April 2022 - present"
        featuredLink:
          enable: false
        content: "I am currently working as a software and FPGA developer at [Carallon Ltd.](https://www.carallon.com/) in London, UK. I am currently working on a project that will significantly improve the usability of the Brompton Tessera video porccessing system in future firmware releases."
      

  # Education
  education:
    enable: false
    # index: true
    items:
      - title: "Master of Business Administration"
        school:
          name: "University of California, Berkeley"
          url: "https://example.org"
        date: "2013 - 2015"
        GPA: "3.8 out of 5.0"
        content: |-
          Extracurricular Activities
            - Lorem ipsum dolor sit amet consectetur adipisicing elit. 
            - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
      - title: "Bachelor of Science in Computer Science"
        school:
          name: "Massachusetts Institute of Technology"
          url: "https://example.org"
        date: "2009 - 2013"
        GPA: "3.9 out of 5.0"
        content: |-
          I Publiced two papers in the ACM SIGCHI Conference on Artificial Intelligence.
          - [Fast and Accurate Object Detection with a Single Convolutional Neural Network](https://example.com)
          - Face mask detection using a single convolutional neural network.

          Extracurricular Activities
            - Lorem ipsum dolor sit amet consectetur adipisicing elit. 
            - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
        featuredLink:
          enable: true
          name: "My academic record"
          url: "https://example.com"
      - title: "High School"
        school:
          name: "Thomas Jefferson High School for Science and Technology."
          url: "https://example.org"
        GPA: "4.2 out of 5.0"
        featuredLink:
          enable: true
          url: "https://example.com"

  # Achievements
  achievements:
    enable: false
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://example.com
      - title: Facebook Hackathon Winner
        content: Developed a product using Artificial Intelligence.
      - title: Hugo Profile
        content: Developed a theme and getting 1K+ downloads per month.
        url: "https://github.com/gurusabarish/hugo-profile"
      - title: Microsoft Imagine Runner
        content: We are developed a product which can help others.
      - title: Google Summer of Code
        content: Contributed to a open source project.
        url: https://example.com

  # projects
  projects:
    enable: false
    items:
      - title: Hugo Profile
        content: A highly customizable and mobile first Hugo template for personal portfolio and blog.
        image: /images/projects/profile.png
        featured:
          name: Demo
          link: https://hugo-profile.netlify.app
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          - icon: fa fa-envelope
            url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          - icon: fab fa-github
            url: https://github.com/gurusabarish/hugo-profile
          - icon: fab fa-twitter
            url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: Image Converter
        content: A web app to convert image to pdf, png to jpg, png to jpg and png to webp without database using django.
        image: /images/projects/converter.jpg
        featured:
          name: Demo
          link: https://django-converter.herokuapp.com
        # badges:
        #   - "Django"
        #   - "Bootstrap"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/converter

      - title: Hugo Profile V2
        content: A clean and simple Hugo template for personal portfolio and blog.
        image: /images/projects/profile2.jpg
        featured:
          name: Demo V2
          link: https://hugo-profile-2.netlify.app
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  contact:
    enable: true
    content: Whether you have a question or just want to say hi, I’ll try my best to get back to you quickly!
    email: vs419@ic.ac.uk
    btnName: Mail me

  footer:
    recentPosts: false
    socialNetworks:
      github: https://github.com
      linkedin: https://linkedin.com
      twitter: https://twitter.com
      instagram: https://instagram.com
      facebook: https://facebook.com
